# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='example.proto',
  package='example',
  syntax='proto3',
  serialized_pb=_b('\n\rexample.proto\x12\x07\x65xample\"\x1e\n\x0e\x45xampleRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1c\n\x0c\x45xampleReply\x12\x0c\n\x04name\x18\x01 \x01(\t2S\n\x0e\x45xampleService\x12\x41\n\rExampleMethod\x12\x17.example.ExampleRequest\x1a\x15.example.ExampleReply\"\x00\x62\x06proto3')
)




_EXAMPLEREQUEST = _descriptor.Descriptor(
  name='ExampleRequest',
  full_name='example.ExampleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='example.ExampleRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=56,
)


_EXAMPLEREPLY = _descriptor.Descriptor(
  name='ExampleReply',
  full_name='example.ExampleReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='example.ExampleReply.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=86,
)

DESCRIPTOR.message_types_by_name['ExampleRequest'] = _EXAMPLEREQUEST
DESCRIPTOR.message_types_by_name['ExampleReply'] = _EXAMPLEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExampleRequest = _reflection.GeneratedProtocolMessageType('ExampleRequest', (_message.Message,), dict(
  DESCRIPTOR = _EXAMPLEREQUEST,
  __module__ = 'example_pb2'
  # @@protoc_insertion_point(class_scope:example.ExampleRequest)
  ))
_sym_db.RegisterMessage(ExampleRequest)

ExampleReply = _reflection.GeneratedProtocolMessageType('ExampleReply', (_message.Message,), dict(
  DESCRIPTOR = _EXAMPLEREPLY,
  __module__ = 'example_pb2'
  # @@protoc_insertion_point(class_scope:example.ExampleReply)
  ))
_sym_db.RegisterMessage(ExampleReply)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class ExampleServiceStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.ExampleMethod = channel.unary_unary(
          '/example.ExampleService/ExampleMethod',
          request_serializer=ExampleRequest.SerializeToString,
          response_deserializer=ExampleReply.FromString,
          )


  class ExampleServiceServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def ExampleMethod(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_ExampleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'ExampleMethod': grpc.unary_unary_rpc_method_handler(
            servicer.ExampleMethod,
            request_deserializer=ExampleRequest.FromString,
            response_serializer=ExampleReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'example.ExampleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaExampleServiceServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def ExampleMethod(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaExampleServiceStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def ExampleMethod(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    ExampleMethod.future = None


  def beta_create_ExampleService_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('example.ExampleService', 'ExampleMethod'): ExampleRequest.FromString,
    }
    response_serializers = {
      ('example.ExampleService', 'ExampleMethod'): ExampleReply.SerializeToString,
    }
    method_implementations = {
      ('example.ExampleService', 'ExampleMethod'): face_utilities.unary_unary_inline(servicer.ExampleMethod),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_ExampleService_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('example.ExampleService', 'ExampleMethod'): ExampleRequest.SerializeToString,
    }
    response_deserializers = {
      ('example.ExampleService', 'ExampleMethod'): ExampleReply.FromString,
    }
    cardinalities = {
      'ExampleMethod': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'example.ExampleService', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
